language: node_js
branches:
  only:
  - src
node_js:
  - "node"
script:
  - "npm test"
  - "npm run build"
cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: "build"
  target_branch: master
  on:
    tags: true