language: node_js
branches:
  only:
  - master
node_js:
- "node"
cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: "build"
  target_branch: gh-pages
  on:
    branch: master
